name: atlas-net-v2

_target_: learnableearthparser.model.AtlasNetV2

transformations:
  - affine_L
  - translation_L
callbacks:
  curriculum:
    order:
    - decay_10

S: ${model.K}

defaults:
  - protos/atlasnet-v2