hydra: 
  searchpath:
      - file://EarthParserDataset/configs
  run:
    # Configure output dir of each experiment programmatically from the arguments
    dir: outputs/postprocs/${now:%d.%b.%y-%H:%M:%S.%f}
  job:
    chdir: True

# Global configurations shared between different modules
experiment: default
profile: False
seed: 4321 # 0 stands for not fixing the seed
mode: test

postproc:
  metric: chamfer4D # or chamfer
  root: "" # root path of the experiments
  thresh: 0.05

# Composing nested config with default
defaults:
  - _self_
  - model/learnableearthparser
  - trainer/default
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog